-- Crear tabla nutricionista
CREATE TABLE nutricionista (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    numero_licencia VARCHAR(50) NOT NULL UNIQUE,
    especialidad VARCHAR(100),
    email VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    activo BOOLEAN NOT NULL,
    PRIMARY KEY (id)
);

-- Crear tabla paciente
CREATE TABLE paciente (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR(100) NOT NULL,
    apellido VARCHAR(100) NOT NULL,
    fecha_nacimiento DATE,
    email VARCHAR(150) NOT NULL UNIQUE,
    telefono VARCHAR(20),
    activo BOOLEAN NOT NULL,
    nutricionista_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (nutricionista_id) REFERENCES nutricionista(id)
);

-- Crear tabla nota
CREATE TABLE nota (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(255) NOT NULL,
    contenido TEXT NOT NULL,
    fecha_creacion TIMESTAMP NOT NULL,
    tipo_nota VARCHAR(50),
    paciente_id BIGINT NOT NULL,
    nutricionista_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (paciente_id) REFERENCES paciente(id),
    FOREIGN KEY (nutricionista_id) REFERENCES nutricionista(id)
);

-- Crear tabla medicion
CREATE TABLE medicion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    peso DOUBLE NOT NULL,
    altura DOUBLE NOT NULL,
    circunferencia_cintura DOUBLE,
    circunferencia_cadera DOUBLE,
    porcentaje_grasa_corporal DOUBLE,
    paciente_id BIGINT NOT NULL,
    nutricionista_id BIGINT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (paciente_id) REFERENCES paciente(id),
    FOREIGN KEY (nutricionista_id) REFERENCES nutricionista(id)
);